# https://github.com/marketplace/actions/checkout
# https://github.com/marketplace/actions/checkout-node-project

name: ğŸ‘¨â€ğŸ’»ğŸ”„Frontend Continuous Integration 

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - 'starter/frontend/**' # Trigger only if files in the frontend directory changes

jobs:
  Setup:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“‚ Checkout Repository
        uses: actions/checkout@v4
      
      - name: ğŸš€ Install Node.js and Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json

      - name: ğŸ“¦ Install Project Dependencies
        working-directory: starter/frontend
        run: npm ci

  Linting:
    runs-on: ubuntu-latest
    needs: Setup  # Ensures that the setup job completes first

    steps:
      - name: ğŸ” Run Lint
        run: npm run lint --prefix starter/frontend

  UnitTests:
    runs-on: ubuntu-latest
    needs: Setup  # Ensures that the setup job completes first

    steps:
      - name: ğŸ§ª Run Tests
        run: npm test --prefix starter/frontend

  Build:
    runs-on: ubuntu-latest
    needs: [Linting, UnitTests]  # Runs only after lint and test jobs succeed

    steps:
      - name: ğŸ“‚ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ³ Build and Cache Docker Image
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache  # Cache path for Docker layers
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: ğŸ³ Build and Run Docker Image
        run: |
          cd starter/frontend
          docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .
          docker run --name mp-frontend -p 3000:3000 -d mp-frontend
